version: '3'

services:
###> doctrine/doctrine-bundle ###
  app:
    container_name: todolist-symfony
    image: sha256:0070a3d08bf3bb7ee56ce151d12f94254412993ae088d5f43bfaeef620eb392f
    ports:
      - "8080:80"



volumes:
  db-data:
